const semaines = [
  {
    id: 202325,
    name: "S25",
    done: " Lundi : Matin : Le Havre - relevés sur site, prépa install laveuse + plieuses , après midi : bureau, suivis occitane, Vichy, prépa Boulogne, Cases ; Mardi : matin : Bureau Epone : prépa réunion APHP, cases, prépa Béthune.... ; après midi réunion APHP  ; Mercredi : Màj documents APHP, CR APHP, prépa intervention.. , ANETT Vichy : avenant, prépa install (échanges entre machines..)     ",
    jours: " Lundi 0,5 + Mardi 1 + Mercredi 0,5 + Jeudi 1 + Vendredi 1 ",
    suite: "--",
    notes: "Jours stockés précédemment = 6 === ",
  },
  {
    id: 202324,
    name: "S24",
    done: " Lundi : Occitane, gestion chantier, compliqué.. / prépa CH CAUDAN ; Mardi : Occitane :  suivi chantier , prépa CH AIX .. Mercredi : KALHYGE Vichy suivi chantier, CR et Planning CH AIX, Suivis Kalhyge périgueux à distance, divers .. ; Jeudi : Boulogne sur Mer , préparation, convocation réunion sur site, visite avec Nico DDC, visite préalable.. Suivis Kalhyge périgueux et Occitane à distance ; Vendredi : màj planning Boulogne sur Mer , PPSPS, préparation installation, Suivis Kalhyge périgueux et Occitane à distance ; Essayer de trouver solution Kalhyge Béthune.. en cours .. Divers ..   ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 1 + Jeudi 0,5 + Vendredi 1 ",
    suite: "--",
    notes: "Jours stockés précédemment = 3,5 + 2,5 === 6",
  },
  {
    id: 202323,
    name: "S23",
    done: " Lundi : Bureau Epône : Occitane (goulotte ... +++ ) , décallage Boulogne, Khalyge Vichy .. ; Mardi/Mercredi : Occitane suivis chantier, gros bordel.. + recallage Boulognne + divers ; Jeudi : Bureau , suivis du bordel d'occitane à distance + divers , problème pour caller Béthune.. , recallage Jenway Périgueux ; Vendredi matin, encore du bordel de l'occitane......  ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 1 + Jeudi 1 + Vendredi 0 ",
    suite: "--",
    notes: "Jours stockés précédemment = 1,5 + 2 === 3,5",
  },
  {
    id: 202322,
    name: "S22",
    done: " Mardi : suivi chantier KALHYGE Vichy, réorganisation installation cause pas de calandre, divers autre.. ; Mercredi : Réunion de lancement CH CAUDAN, visite du site, prise en main projet, divers autre.. ; Jeudi : préparation AIX + AVIGNON, gestion OCCITANE urgence, pas de goulotte ni bac !! , divers ; Vendredi : Visite CH AIX, relevés et vérifs sur site prépa planning avec client, prise en main projet, prépa installation , Visite CH AVIGNON, relevés et vérifs sur site prépa planning avec client, prise en main projet ...    ",
    jours: " Mardi 1 + Mercredi 1 + Jeudi 0,5 + Vendredi 1 ",
    suite: "--",
    notes: "Jours stockés précédemment = 10,5 => Facturés 10,5 ===> 0 + 1,5 === 1,5",
  },
  {
    id: 202321,
    name: "S21",
    done: " Lundi : prépa Périgueux Jenway, prépa KALHYGE Vichy, Occitane, Boulogne (trou, elec, féraille ..).. emails..  ; Mardi : Littoral (thomas, aspi, MES séchoir ..), Prise en main Avignon .. Mercredi : Teams Kalhyge Béthune ; Jeudi : Point MILL plan archi, ajustement process, Problème K Vichy pas de calandre : réorga ..... ,  LITTORAL point sur site avec client et Thomas, liste réserves, PV MES.. ; Vendredi : Point planning Littoral plat , préparation installation    ",
    jours: " Lundi 1 + Mardi 1 + Jeudi 1 + Vendredi 0,5",
    suite: "--",
    notes: "Jours stockés précédemment = 9 + 1,5 === 10,5 ",
  },
  {
    id: 202320,
    name: "S20",
    done: " Lundi : Gestion MES Grenoble + MES APHP , prise en main AIX, divers ; Mercredi : prépa Occitane / Littoral / Boulogne .. divers..   ",
    jours: " Lundi 1 + Mercredi 1  ",
    suite: "--",
    notes: "Jours stockés précédemment = 9 + 0 === 9",
  },
  {
    id: 202319,
    name: "S19",
    done: " Lundi : Périgueux suivi chantier, prépa switch Express, Prise en main KALHYGE Béthune (très en retard)  , ratrapage emails.., Grenoble prépa chantier PPSPS,; Mardi, Périgueux démarage, APHP réunion teams ......., divers ++ ; Mercredi après midi : Litto planning, gestion des merdes, inter QSP, .. prépa APHP et Grenoble, Occitane, Boulogne, ... ; Jeudi : APHP encore réunion sécu/formation.... suivi chantier , gestion pb Grenoble (pas de tapis!) , suivi Litto QSP , ; Vendredi :  tri emails/orga.. , Grenoble suivi chantier , APHP suivi chantier + documents ; Samedi : Suivi chantiers Grenoble/APHP + documents APHP..  ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 0,5 + Jeudi 1 + Vendredi 1 + Samedi 0,5  ",
    suite: "--",
    notes: "Jours stockés précédemment = 6 + 3 === 9",
  },
  {
    id: 202318,
    name: "S18",
    done: " Mercredi : Littoral suivi chantier + divers ; Jeudi : Littoral suivi chantier , réunion / organisation suite (finition) , besoin avancer.. pb K Vichy calandre ; Vendredi : Périgueux, démmarage chantier, suivi chantier, Littoral : problème MES séchoir ... 1,3bar dans réseau, replanification MES séchoir + complément formation, Planification finition, essayer d'avancer finition .. compliqué.. Divers/tri/réorga.. Samedi : Suivi chantier, prépa APHP + N Squivay ; Dimanche : suivi chantier , APHP formation ..   ",
    jours: " Mercredi 1 + Jeudi 1 + Vendredi 1 (+Samedi 0,5 + Dimanche 0,5) = 4 ",
    suite: "--",
    notes: "Jours stockés précédemment = 4 + 2 == 6 ",
  },
  {
    id: 202317,
    name: "S17",
    done: " Lundi = Littoral : check install Futurail avec Yann (manque capteurs ..), check raccordements , divers.. ; Mardi : Livraisons Littoral, suivis chantier, pb tunnel Occitane , divers .. ; Jeudi = Epone : Suivis Littoral, pb pompe, capteur , cabine..!  .. , planification Périgueux Jenway, planification Périgueux Express, Grenoble PPSPS, divers..  ; Vendredi = Epone : Littoral pb JEDE .... , suivis chantier.. , prépa Périgueux, prépa déplacements , divers.. ",
    jours: " Lundi + Mardi + Jeudi + Vendredi = 4 ",
    suite: "--",
    notes: "Avril : S14 = 3.5, S15 = 0, S16 = 3, S17 = 4 // Stocké => 1.5 + 1.5 -2 + 1 + 2 = 4 ",
  },
  {
    id: 202316,
    name: "S16",
    done: " Lundi : Boulogne : prépa install Holdam, APAVE, trou.. // Périgueux, gérer pb jenway, jenassist .. // check Grenoble // divers .. ; Mardi : APHP : Plan de prévention pingpong Thery.. doc formation... Périgueux , solution Jenway échanges usines/client .. , Littoral check cliente avant install , check divers , prépa plat .. , prépa visite Anett Vichy ; Vendredi : visite ANETT Vichy + Glen, check implantation, passage machines, option DK, change order, com viking ..divers  ",
    jours: " Lundi + Mardi + Vendredi = 3 ",
    suite: "--",
    notes: "Avril : S14 = 3.5, S15 = 0, S16 = 3 // Stocké => 1.5 + 1.5 -2 + 1 = 2 ",
  },
  {
    id: 202315,
    name: "S15",
    done: " Suivi/emails.. ",
    jours: " = 0 ",
    suite: "--",
    notes: "Avril : S14 = 3.5 S15 = 0 // Stocké => 1.5 + 1.5 -2 = 1 ",
  },
  {
    id: 202314,
    name: "S14",
    done: " Lundi visite K Périgueux + Glen, check implantation, check manut +Herrewyn, planning et points techniques avec client ... ; Mardi : visite MILL, prise en main, check existant, réunion avec intervenants ; Mercredi : CR MILL, phasage, check points techniques, check surcoûts, décalages ExW, ... APHP : CR ++, plannification manut, prépa documents.... Vendredi : Litto transport, Périgueux protections, emails + divers.. ; Dimanche : APHP : préparation documents formation, utilisation, sécurité..  ",
    jours: "Lundi = 1 (intégration des 3h de Vendredi S13) ; Mardi = 0,5 ; Mercredi = 1 ; Vendredi + Dimanche = 1 ",
    suite: "--",
    notes: "Avril : S14 = 3.5 // Stocké => 1.5 + 1.5 = 3 ",
  },
  {
    id: 202313,
    name: "S13",
    done: " Mardi Epone : Boulogne équipes / planning / prépa // Occitane TW ... // divers suivis emails ...  ; Jeudi Epone , revue projet , prépa visites APHP/Périgueux/MILL ...",
    jours: "Mardi =1 + Jeudi =1 + (Vendredi 3h)",
    suite: "--",
    notes: "Mars : S09=1+0,5 ; S10=2+0,5 ; S11=2 === 2j/semaine ; S12 === 3.5 S13 ===2 // Stocké => 1.5j  ",
  },
  {
    id: 202312,
    name: "S12",
    done: " Lundi : visite KALHYGE Vichy, check manut, check Siler, planning , réunion coordination ; Mardi : visite Occitane, check manut, check implantation, prépa planning, point avec client ; Jeudi Epone , Check Annet Vichy Glen, prise en main APHP, check point techniques, OCCITANE , planning .... plan raccordement, màj plan, check points techniques, K Périgueux check Glen ; Vendredi Epone : Occitane validation planning, check TW JM service, màj équipe // Litto prépa chantier nacelles, check planDk // APHP : établissement planning, équipes // MILL : prépa visite // Périgueux check plan + prépa visite // Boulogne : équipes (NS, DK..) //.....  ",
    jours: "Lundi 0,5 + Mardi =1 avec les 3h de Grenoble + Jeudi =1 + Vendredi =1",
    suite: "--",
    notes: "Mars : S09=1+0,5 ; S10=2+0,5 ; S11=2 === 2j/semaine ; S12 === 3.5 // Stocké => 1.5j  ",
  },
  {
    id: 202311,
    name: "S11",
    done: " Grenoble : planning validé, équipes plannifiées, ~débriefé, màj OC DK/PMV, point client... // Littoral : problème poteaux réglé, point tuyauterie ATIS.. // Vichy : prépa visite, !check SILER, prépa planning, // Boisset : Point client/INWATEC ok , clarification fonctionnement //  Occitane : prépa visite ",
    jours: "Mardi + Jeudi",
    suite: "--",
    notes: "Mars : S09=1+0,5 S10=2+0,5 S11=2 === 2j/semaine (+ compte 3h qui trainent pour la visite de Grenoble, on verra ce que j'en fait, je ne te facture pas le temps en voiture pour cette journée ) ",
  },
  {
    id: 202310,
    name: "S10",
    done: "L : Grenoble prépa visite, check plan, check possibilité planning/équipes.. Sodi..Kanne..; contact Occitane ; check INWATEC Boisset ... ,Périgueux check CDC/contract ; Mardi : point sur site avec client, check implantation, check manutention..  ; Mercredi : Point BOISSET/INWATEC/THERMOPATCH , CR Grenoble, propo planning , check commandes, check fonctionnement .. Vendredi matin : Grenoble++ planning, interférences Kanne/sodi, réponse client, plans, modif tapis.. Boisset échanges INW/client ..   ",
    jours: "Lundi + 3H Mardi [visite Grenoble]//temps en voiture pas compté + Mercredi + Vmatin  ",
    suite: "--",
    notes: "Mars : à facturer, en cours fin de semaine : S09=1+0,5 S10=2+0,5 == 4 jours (+ compte 3h qui trainent pour la visite de Grenoble, on verra ce que j'en fait, je ne te facture pas le temps en voiture pour cette journée ) ",
  },
  {
    id: 202309,
    name: "S09",
    done: "L : prise en main Boulogne, prépa réunion, consult DDC, suivi Litto, prise en main Grenoble.. M : visite Boulogne, check manut, réunion projet, check points techniques sur site .. J : planning Boulogne + commandes + check ss traitants, prépa install // Périgueux : descriptif DK, check Grenoble Glen, Littoral modif planning, check possibilités .. Vmatin : Littoral màj planning, màj équipes, check dispos.. Vichy prépa .. ",
    jours: "Lundi + Mardi + J + Vmatin ",
    suite: "--",
    notes: "-- ",
  },
  {
    id: 202308,
    name: "S08",
    done: " L: Littoral : Planning, QSP, HERREWYN, STS, JEFR+DE, consult FRADIN charp // Vichy confirmation fonctionnement DK, prise en main projet // périgueux planification équipe .. ; Mardi : check ttes dates install, point planning Gianni  consult CSB .., occitane prise en main dossier (PMV..), début planif K Vichy..; Jeudi : visite Littoral, check avec tuyauteur, point client (découpe..), check manut ; Vendredi : réunion Littoral, planning d'installation, clarification découpe + points techniques .. traçage fosses.. incertitudes implantation TGP.. ",
    jours: "Lundi + Mardi + Jeudi + Vendredi => facturé 4 jours",
    suite: "--",
    notes: "-- ",
  },
  {
    id: 202307,
    name: "S07",
    done: " Récupération liste et données projets, prise en main Littoral : préparaion et proposition planning, orga réunion, check plan structure avec FC (!), avance EW Z1200, Boulogne : check plan avec JC, échanges avec AP:validation => change order demande en cours ",
    jours: "3 jours : mardi, mercredi, jeudi (+bricoles Vendredi) => facturé 3 jours",
    suite: "Planifier équipes ; débriefer..",
    notes: "",
  },
];

export default semaines;