const semaines = [
  {
    id: 202339,
    name: "S39",
    done: " Lundi : Project review, débrief aix, suivis chantier Périgueux, prépa avignon, débrief poitier METRIC ; Mardi : CAUDAN point PMV / SODILEC / Plans , Grenoble (pas simple pour des bricoles ...), / point case/CRN ; Mercredi matin : Point INWATEC avec nouveau PM INWATEC (Kasper resigned) , Teams Maria Limoges + prépa projet, Grenoble, Périgueux suivi + réserves (y compris train MP) ; Mercredi matin : Le Havre planification, CAUDAN prépa, POITIER prépa, Cherbourg prépa   ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 0,5 + Jeudi 0,5  + Vendredi 0 ",
    suite: "--",
    notes: "Jours stockés précédemment = 5 + 1 === 6 ",
    njours: 3,
  },
  {
    id: 202338,
    name: "S38",
    done: " Lundi : Préparation CAUDAN (PMV), divers ; Mardi : Divers Périgueux, LH, Caudan ; Mercredi : Prépa ANETT Vichy, divers CAUDAN, CHERBOURG ..  ; Jeudi : Grenoble réserves, Caudan, ANETT Vichy , divers ; Vendredi/WE : Suivi à distance Périgueux ",
    jours: " Lundi 0,5 + Mardi 0,5 + Mercredi 1 + Jeudi 1  + Vendredi 0 ",
    suite: "--",
    notes: "Jours stockés précédemment = 4 + 1 === 5 ",
    njours: 3,
  },
  {
    id: 202337,
    name: "S37",
    done: " Lundi : Epone : Préparation CAUDAN + Périgueux Express et réserves ; Mardi : visite sur site CAUDAN avec N.Giordani et P.Herrewyn, préparation manutention et chantier ; Mercredi : CAUDAN réunion de coordination / préparation chantier  ; Jeudi : CR CAUDAN et préparation ; Vendredi CR CAUDAN et préparation  ",
    jours: " Lundi 0,5 + Mardi 1 + Mercredi 1 + Jeudi 0,5  + Vendredi 0,5 ",
    suite: "--",
    notes: "Jours stockés précédemment = 2,5 + 1,5 === 4 ",
    njours: 3.5,
  },
  {
    id: 202336,
    name: "S36",
    done: " Lundi : Préparation CAUDAN + BOISSET ; Mardi : Préparation CAUDAN , LH , Poitier METRIC ; Mercredi : check Cherbourg, nettoyage cases/CRN, traitement emails.. ; Jeudi : Préparation CAUDAN, réception K Vichy, divers  ",
    jours: " Lundi 0,5 + Mardi 0,5 + Mercredi 0,5 + Jeudi 0,5  + Vendredi 0 ",
    suite: "--",
    notes: "Jours stockés précédemment = 2,5 + 0 === 2,5 ",
    njours: 2,
  },
  {
    id: 202335,
    name: "S35",
    done: " Lundi : reprise Epône tri email, point planning Gianni, récupération et préparation PC JENSEN.. point poitier/caudan avec Yann.. ; Mardi : préparation Avignon, reprise en main divers planning.. préparation Le Havre ; Mercredi : prépa LH / Poitier / CAUDAN ; Jeudi : prépa périgueux remplacement Express, prépa CAUDAN, Boulogne prépa réception / DOE , divers... ; Vendredi : Préparation CAUDAN / Le Havre  ",
    jours: " Lundi 0,5 + Mardi 0,5 + Mercredi 1 + Jeudi 1 + Vendredi 0,5 ",
    suite: "--",
    notes: "Jours stockés précédemment = 1 + 1,5 === 2,5 ",
    njours: 3.5,
  },
  {
    id: 202334,
    name: "S34",
    done: "  ",
    jours: "  ",
    suite: "--",
    notes: "Jours stockés précédemment = 3 - 2 === 1 ",
    njours: 0,
  },
  {
    id: 202333,
    name: "S33",
    done: "  ",
    jours: "  ",
    suite: "--",
    notes: "Jours stockés précédemment = 5 - 2 === 3 ",
    njours: 0,
  },
  {
    id: 202332,
    name: "S32",
    done: " Mercredi : traitement email, bricoles divers ; Vendredi : Visite Poitier : point avec client, relevés, préparations projets (METRIC + CARTWASH), pas mal de détails à vérifier sur les deux sujets ",
    jours: " Mercredi 0 + Vendredi 1 ",
    suite: "--",
    notes: "Jours stockés précédemment = 6 - 1 === 5 ",
    njours: 1,
  },
  {
    id: 202331,
    name: "S31",
    done: " Lundi : CR et phasage MILL Service ; Jeudi : Bureau Epone : Cherbourg préparation, Littoral avec SAV... , Poitier : préparation installation et visite semaine pro, Suivi APHP charly sur site.. ; Vendredi matin : Préparation Poitier (+ Cartwash ..); CH CAUDAN préparation / consultations ; préparation Boisset INWATEC  ",
    jours: " Lundi 0,5 + Mardi 0 + Mercredi 0 + Jeudi 1 + Vendredi 0,5 ",
    suite: "--",
    notes: "Jours stockés précédemment = 6 + 0 === 6 ",
    njours: 2,
  },
  {
    id: 202330,
    name: "S30",
    done: " Lundi : CH BOULOGNE : Mise en service, prise en main réserves COFITEX + Client, visite bureau de contrôle et prise en main réserves associés, Nice 2 : préparation installation LC ; CARROS 2 : préparation installation LC3 (teams avec Dominic Weibel, pour install le 1er août ..! déscriptif déroulement => client/Termain ; Mardi : Boulogne résolution réserves, suivi démarrage, préparation Carros 2.. , prépa MILL Service ; Mercredi : prépa visite MILL, suivi distance BOULOGNE, Annulation CARROS 2 3eme aspi (sage décision du client ..!) => Reporté septembre ; point LITTORAL Sammy sur place, CR des réserves et actions effectuées ; Jeudi : Visite MILL service + Glen , réunion coordination avec Client + sous-traitants client, relevés sur site ; Vendredi : MILL service retour + bricoles..  ",
    jours: " Lundi 1 + Mardi 0,5 + Mercredi 0,5 + Jeudi 1 + Vendredi 0 ",
    suite: "--",
    notes: "Jours stockés précédemment = 5 + 1 === 6 ",
    njours: 3,
  },
  {
    id: 202329,
    name: "S29",
    done: " Lundi : Epone : Point MILL avec Glen, prépa MILL ; point CARROS 2 avec Gianni JEDE Raphael pour upgrade séchoirs ; prépa CHERBOURG et CH AIX ; Mardi : Prépa MILL, Prépa Cherbourg, Prépa CAUDAN ; Mercredi : CHERBOURG : viste de préparation avec tuyauteur, electricien, client ; Jeudi : CH BOULOGNE : suivis chantier, Nice 2 : préparation installation LC ; Vendredi : CH BOULOGNE : suivis chantier, Nice 2 : préparation installation LC , Grenoble DK.. , MILL : préparation planification réunion coordination ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 0,5 + Jeudi 0,5 + Vendredi 1 ",
    suite: "--",
    notes: "Jours stockés précédemment = 3 + 2 === 5 ",
    njours: 4,
  },
  {
    id: 202328,
    name: "S28",
    done: " Lundi : Epone : Préparation CH CHERBOURG - CR réunion et planning, consultation pour convoyeurs.. Gestion Littoral à distance ; Mardi EPONE : Littoral : suivi à distance, QSP et Thomas pour lever réserves (+ problèmes sur site) / Préparation CAUDAN / suivi Occitane ; Jeudi : Epône : préparation CAUDAN (planning, points techniques, adaptation metric +++ )  ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 0 + Jeudi 1 + Vendredi 0 ",
    suite: "--",
    notes: "Jours stockés précédemment = 2 + 1 === 3 ",
    njours: 3,
  },
  {
    id: 202327,
    name: "S27",
    done: " Lundi : Epone : préparation revue projet / nettoyage AX , JCH cases .. Occitane protection, divers.. ; Mardi : matin revue de projet, après midi KALHYGE Béthune installation avec Franck ; Mercredi : KALHYGE Béthune installation avec Franck + JEDK en remote + divers ; Jeudi : fin installation KALHYGE Béthune avec Franck + JEDK remote .. (un peu compliqué cette installation, j'avais demandé à JEDK de nous envoyer un programmeur, mais visiblement ce n'était pas prévu, prochaine fois il faudra insister plus, même un truc qui est sensé être simple comme ça c'est galère à distance) + divers ; Vendredi : quelques bricoles..   ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 1 + Jeudi 1 + Vendredi 0 ",
    suite: "--",
    notes: "Jours stockés précédemment = 0 + 2 === 2 ",
    njours: 4,
  },
  {
    id: 202326,
    name: "S26",
    done: " Lundi : Littoral : démarrage, problèmes I5G JECN.. chercher solutions, chercher huile, orga.. Point avec client .. ; Mardi : CH Cherbourg : visite et relevés sur site, réunion lancement avec client + CR, préparation projet et planning, visite + FRADIN pour chiffrage .. ; Mercredi : Bureau(Rennes) Point Anett Vichy avec client, Planning + Gianni + demandes spéciales traitement données... , prépa Kalhyge Béthune avec Franck + DK... , divers Occitane ; Jeudi : Littoral : suivis chantier sur site, point avec cliente, point/prépa réserves, Kalhyge Périgueux prépa Express+visite contrôle , Kalhyge Vichy .. ; Vendredi : CH CAUDAN : point sur site avec Fraçois, prépa install , planning , relevés ..   ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 0,5 + Jeudi 1 + Vendredi 0,5 ",
    suite: "--",
    notes: "Jours stockés précédemment = 8 + 2 === 10 ",
    njours: 4,
  },
  {
    id: 202325,
    name: "S25",
    done: " Lundi : Matin : Le Havre - relevés sur site, prépa install laveuse + plieuses , après midi : bureau, suivis occitane, Vichy, prépa Boulogne, Cases ; Mardi : matin : Bureau Epone : prépa réunion APHP, cases, prépa Béthune.... ; après midi réunion APHP  ; Mercredi : Màj documents APHP, CR APHP, prépa intervention.. , ANETT Vichy : avenant, prépa install (échanges entre machines..) ; Jeudi : Littoral suivis/organisation chantier, 3h à remplir un constat avec le chauffeur bielorusse qui a des papiers Polonais qui a accroché la voiture de la voisine, Re planification KALHYGE Béthune, préparation ANETT Vichy , traitement emails, divers..  ; Vendredi : Littoral suivis chantier, prépa Boulogne sur Mer (féraillage, décallage .. ), prépa Anett Vichy, prépa Caudan  ",
    jours: " Lundi 0,5 + Mardi 1 + Mercredi 0,5 + Jeudi 1 + Vendredi 1 ",
    suite: "--",
    notes: "Jours stockés précédemment = 6 + 2 === 8 ",
    njours: 4,
  },
  {
    id: 202324,
    name: "S24",
    done: " Lundi : Occitane, gestion chantier, compliqué.. / prépa CH CAUDAN ; Mardi : Occitane :  suivi chantier , prépa CH AIX .. Mercredi : KALHYGE Vichy suivi chantier, CR et Planning CH AIX, Suivis Kalhyge périgueux à distance, divers .. ; Jeudi : Boulogne sur Mer , préparation, convocation réunion sur site, visite avec Nico DDC, visite préalable.. Suivis Kalhyge périgueux et Occitane à distance ; Vendredi : màj planning Boulogne sur Mer , PPSPS, préparation installation, Suivis Kalhyge périgueux et Occitane à distance ; Essayer de trouver solution Kalhyge Béthune.. en cours .. Divers ..   ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 1 + Jeudi 0,5 + Vendredi 1 ",
    suite: "--",
    notes: "Jours stockés précédemment = 3,5 + 2,5 === 6",
    njours: 4.5,
  },
  {
    id: 202323,
    name: "S23",
    done: " Lundi : Bureau Epône : Occitane (goulotte ... +++ ) , décallage Boulogne, Khalyge Vichy .. ; Mardi/Mercredi : Occitane suivis chantier, gros bordel.. + recallage Boulognne + divers ; Jeudi : Bureau , suivis du bordel d'occitane à distance + divers , problème pour caller Béthune.. , recallage Jenway Périgueux ; Vendredi matin, encore du bordel de l'occitane......  ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 1 + Jeudi 1 + Vendredi 0 ",
    suite: "--",
    notes: "Jours stockés précédemment = 1,5 + 2 === 3,5",
    njours: 4,
  },
  {
    id: 202322,
    name: "S22",
    done: " Mardi : suivi chantier KALHYGE Vichy, réorganisation installation cause pas de calandre, divers autre.. ; Mercredi : Réunion de lancement CH CAUDAN, visite du site, prise en main projet, divers autre.. ; Jeudi : préparation AIX + AVIGNON, gestion OCCITANE urgence, pas de goulotte ni bac !! , divers ; Vendredi : Visite CH AIX, relevés et vérifs sur site prépa planning avec client, prise en main projet, prépa installation , Visite CH AVIGNON, relevés et vérifs sur site prépa planning avec client, prise en main projet ...    ",
    jours: " Mardi 1 + Mercredi 1 + Jeudi 0,5 + Vendredi 1 ",
    suite: "--",
    notes: "Jours stockés précédemment = 10,5 => Facturés 10,5 ===> 0 + 1,5 === 1,5",
    njours: 3.5,
  },
  {
    id: 202321,
    name: "S21",
    done: " Lundi : prépa Périgueux Jenway, prépa KALHYGE Vichy, Occitane, Boulogne (trou, elec, féraille ..).. emails..  ; Mardi : Littoral (thomas, aspi, MES séchoir ..), Prise en main Avignon .. Mercredi : Teams Kalhyge Béthune ; Jeudi : Point MILL plan archi, ajustement process, Problème K Vichy pas de calandre : réorga ..... ,  LITTORAL point sur site avec client et Thomas, liste réserves, PV MES.. ; Vendredi : Point planning Littoral plat , préparation installation    ",
    jours: " Lundi 1 + Mardi 1 + Jeudi 1 + Vendredi 0,5",
    suite: "--",
    notes: "Jours stockés précédemment = 9 + 1,5 === 10,5 ",
    njours: 3.5,
  },
  {
    id: 202320,
    name: "S20",
    done: " Lundi : Gestion MES Grenoble + MES APHP , prise en main AIX, divers ; Mercredi : prépa Occitane / Littoral / Boulogne .. divers..   ",
    jours: " Lundi 1 + Mercredi 1  ",
    suite: "--",
    notes: "Jours stockés précédemment = 9 + 0 === 9",
    njours: 2,
  },
  {
    id: 202319,
    name: "S19",
    done: " Lundi : Périgueux suivi chantier, prépa switch Express, Prise en main KALHYGE Béthune (très en retard)  , ratrapage emails.., Grenoble prépa chantier PPSPS,; Mardi, Périgueux démarage, APHP réunion teams ......., divers ++ ; Mercredi après midi : Litto planning, gestion des merdes, inter QSP, .. prépa APHP et Grenoble, Occitane, Boulogne, ... ; Jeudi : APHP encore réunion sécu/formation.... suivi chantier , gestion pb Grenoble (pas de tapis!) , suivi Litto QSP , ; Vendredi :  tri emails/orga.. , Grenoble suivi chantier , APHP suivi chantier + documents ; Samedi : Suivi chantiers Grenoble/APHP + documents APHP..  ",
    jours: " Lundi 1 + Mardi 1 + Mercredi 0,5 + Jeudi 1 + Vendredi 1 + Samedi 0,5  ",
    suite: "--",
    notes: "Jours stockés précédemment = 6 + 3 === 9",
    njours: 5,
  },
  {
    id: 202318,
    name: "S18",
    done: " Mercredi : Littoral suivi chantier + divers ; Jeudi : Littoral suivi chantier , réunion / organisation suite (finition) , besoin avancer.. pb K Vichy calandre ; Vendredi : Périgueux, démmarage chantier, suivi chantier, Littoral : problème MES séchoir ... 1,3bar dans réseau, replanification MES séchoir + complément formation, Planification finition, essayer d'avancer finition .. compliqué.. Divers/tri/réorga.. Samedi : Suivi chantier, prépa APHP + N Squivay ; Dimanche : suivi chantier , APHP formation ..   ",
    jours: " Mercredi 1 + Jeudi 1 + Vendredi 1 (+Samedi 0,5 + Dimanche 0,5) = 4 ",
    suite: "--",
    notes: "Jours stockés précédemment = 4 + 2 == 6 ",
    njours: 4,
  },
  {
    id: 202317,
    name: "S17",
    done: " Lundi = Littoral : check install Futurail avec Yann (manque capteurs ..), check raccordements , divers.. ; Mardi : Livraisons Littoral, suivis chantier, pb tunnel Occitane , divers .. ; Jeudi = Epone : Suivis Littoral, pb pompe, capteur , cabine..!  .. , planification Périgueux Jenway, planification Périgueux Express, Grenoble PPSPS, divers..  ; Vendredi = Epone : Littoral pb JEDE .... , suivis chantier.. , prépa Périgueux, prépa déplacements , divers.. ",
    jours: " Lundi + Mardi + Jeudi + Vendredi = 4 ",
    suite: "--",
    notes: "Avril : S14 = 3.5, S15 = 0, S16 = 3, S17 = 4 // Stocké => 1.5 + 1.5 -2 + 1 + 2 = 4 ",
    njours: 4,
  },
  {
    id: 202316,
    name: "S16",
    done: " Lundi : Boulogne : prépa install Holdam, APAVE, trou.. // Périgueux, gérer pb jenway, jenassist .. // check Grenoble // divers .. ; Mardi : APHP : Plan de prévention pingpong Thery.. doc formation... Périgueux , solution Jenway échanges usines/client .. , Littoral check cliente avant install , check divers , prépa plat .. , prépa visite Anett Vichy ; Vendredi : visite ANETT Vichy + Glen, check implantation, passage machines, option DK, change order, com viking ..divers  ",
    jours: " Lundi + Mardi + Vendredi = 3 ",
    suite: "--",
    notes: "Avril : S14 = 3.5, S15 = 0, S16 = 3 // Stocké => 1.5 + 1.5 -2 + 1 = 2 ",
    njours: 3,
  },
  {
    id: 202315,
    name: "S15",
    done: " Suivi/emails.. ",
    jours: " = 0 ",
    suite: "--",
    notes: "Avril : S14 = 3.5 S15 = 0 // Stocké => 1.5 + 1.5 -2 = 1 ",
    njours: 0,
  },
  {
    id: 202314,
    name: "S14",
    done: " Lundi visite K Périgueux + Glen, check implantation, check manut +Herrewyn, planning et points techniques avec client ... ; Mardi : visite MILL, prise en main, check existant, réunion avec intervenants ; Mercredi : CR MILL, phasage, check points techniques, check surcoûts, décalages ExW, ... APHP : CR ++, plannification manut, prépa documents.... Vendredi : Litto transport, Périgueux protections, emails + divers.. ; Dimanche : APHP : préparation documents formation, utilisation, sécurité..  ",
    jours: "Lundi = 1 (intégration des 3h de Vendredi S13) ; Mardi = 0,5 ; Mercredi = 1 ; Vendredi + Dimanche = 1 ",
    suite: "--",
    notes: "Avril : S14 = 3.5 // Stocké => 1.5 + 1.5 = 3 ",
    njours: 3.5,
  },
  {
    id: 202313,
    name: "S13",
    done: " Mardi Epone : Boulogne équipes / planning / prépa // Occitane TW ... // divers suivis emails ...  ; Jeudi Epone , revue projet , prépa visites APHP/Périgueux/MILL ...",
    jours: "Mardi =1 + Jeudi =1 + (Vendredi 3h)",
    suite: "--",
    notes: "Mars : S09=1+0,5 ; S10=2+0,5 ; S11=2 === 2j/semaine ; S12 === 3.5 S13 ===2 // Stocké => 1.5j  ",
    njours: 2,
  },
  {
    id: 202312,
    name: "S12",
    done: " Lundi : visite KALHYGE Vichy, check manut, check Siler, planning , réunion coordination ; Mardi : visite Occitane, check manut, check implantation, prépa planning, point avec client ; Jeudi Epone , Check Annet Vichy Glen, prise en main APHP, check point techniques, OCCITANE , planning .... plan raccordement, màj plan, check points techniques, K Périgueux check Glen ; Vendredi Epone : Occitane validation planning, check TW JM service, màj équipe // Litto prépa chantier nacelles, check planDk // APHP : établissement planning, équipes // MILL : prépa visite // Périgueux check plan + prépa visite // Boulogne : équipes (NS, DK..) //.....  ",
    jours: "Lundi 0,5 + Mardi =1 avec les 3h de Grenoble + Jeudi =1 + Vendredi =1",
    suite: "--",
    notes: "Mars : S09=1+0,5 ; S10=2+0,5 ; S11=2 === 2j/semaine ; S12 === 3.5 // Stocké => 1.5j  ",
    njours: 3.5,
  },
  {
    id: 202311,
    name: "S11",
    done: " Grenoble : planning validé, équipes plannifiées, ~débriefé, màj OC DK/PMV, point client... // Littoral : problème poteaux réglé, point tuyauterie ATIS.. // Vichy : prépa visite, !check SILER, prépa planning, // Boisset : Point client/INWATEC ok , clarification fonctionnement //  Occitane : prépa visite ",
    jours: "Mardi + Jeudi",
    suite: "--",
    notes: 2,
    njours: 2,
  },
  {
    id: 202310,
    name: "S10",
    done: "L : Grenoble prépa visite, check plan, check possibilité planning/équipes.. Sodi..Kanne..; contact Occitane ; check INWATEC Boisset ... ,Périgueux check CDC/contract ; Mardi : point sur site avec client, check implantation, check manutention..  ; Mercredi : Point BOISSET/INWATEC/THERMOPATCH , CR Grenoble, propo planning , check commandes, check fonctionnement .. Vendredi matin : Grenoble++ planning, interférences Kanne/sodi, réponse client, plans, modif tapis.. Boisset échanges INW/client ..   ",
    jours: "Lundi + 3H Mardi [visite Grenoble]//temps en voiture pas compté + Mercredi + Vmatin  ",
    suite: "((Mars : à facturer, en cours fin de semaine : S09=1+0,5 S10=2+0,5 == 4 jours )) ",
    notes: 2.5,
    njours: 2.5,
  },
  {
    id: 202309,
    name: "S09",
    done: "L : prise en main Boulogne, prépa réunion, consult DDC, suivi Litto, prise en main Grenoble.. M : visite Boulogne, check manut, réunion projet, check points techniques sur site .. J : planning Boulogne + commandes + check ss traitants, prépa install // Périgueux : descriptif DK, check Grenoble Glen, Littoral modif planning, check possibilités .. Vmatin : Littoral màj planning, màj équipes, check dispos.. Vichy prépa .. ",
    jours: "Lundi + Mardi + J + Vmatin ",
    suite: "--",
    notes: 3.5,
    njours: 3.5,
  },
  {
    id: 202308,
    name: "S08",
    done: " L: Littoral : Planning, QSP, HERREWYN, STS, JEFR+DE, consult FRADIN charp // Vichy confirmation fonctionnement DK, prise en main projet // périgueux planification équipe .. ; Mardi : check ttes dates install, point planning Gianni  consult CSB .., occitane prise en main dossier (PMV..), début planif K Vichy..; Jeudi : visite Littoral, check avec tuyauteur, point client (découpe..), check manut ; Vendredi : réunion Littoral, planning d'installation, clarification découpe + points techniques .. traçage fosses.. incertitudes implantation TGP.. ",
    jours: "Lundi + Mardi + Jeudi + Vendredi => facturé 4 jours",
    suite: "--",
    notes: 4,
    njours: 4,
  },
  {
    id: 202307,
    name: "S07",
    done: " Récupération liste et données projets, prise en main Littoral : préparaion et proposition planning, orga réunion, check plan structure avec FC (!), avance EW Z1200, Boulogne : check plan avec JC, échanges avec AP:validation => change order demande en cours ",
    jours: "3 jours : mardi, mercredi, jeudi (+bricoles Vendredi) => facturé 3 jours",
    suite: "Planifier équipes ; débriefer..",
    notes: 3,
    njours: 3,
  },
];

export default semaines;