const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const projectSchema = new Schema({
    today: String,
    nom: String,
    quote: String,
    prixVente: Number,
    margePIF: Number,
    margeCurrent: Number,
    sommeCN: Number,
    sommeDK: Number,
    sommeUS: Number,
    sommeDE: Number,
    sommeIW: Number,
    sommeKANNE: Number,
    sommeSODI: Number,
    sommePMV: Number,
    sommeNUOVA: Number,
    sommeSILER: Number,
    sommeFRADIN: Number,
    sommeOLDAM: Number,
    sommeTCS: Number,
    sommeSATELEC: Number,
    sommeAPAVE: Number,
    warranty: Number,
    services: Number,
    transport: Number,
    lineText1Concatenatedcn: String,
    lineText1Concatenateddk: String,
    lineText1Concatenatedde: String,
    lineText1Concatenatedus: String,
    gaz: Boolean,
    manutention: Number,
    noManut: Number,
    jedkDates: [Date],
    jedeDates: [Date],
    jecnDates: [Date],
    jeusDates: [Date],
    jeiwDates: [Date],
    totalTotal: Number,
    totalCommandes: Number,
    checkSumProject: Boolean,
    newField0: Number,
    newField1: Number,
    newField2: Number,
    newField3: Number,
    newField4: Number,
    newField5: Number,
    newField6: Number,
    newField7: Number,
    newField8: Number,
    newField9: Number,
    dField0: String,
    dField1: String,
    dField2: String,
    dField3: String,
    dField4: String,
    dField5: String,
    dField6: String,
    dField7: String,
    dField8: String,
    dField9: String,
});

const Project = mongoose.model("Project", projectSchema);

module.exports = Project;